name: 'Get & Cache Dependencies'
description: 'Get dependencies (via npm) and cache them'
runs:
  using: 'composite' # composite is a keyword
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci 
      shell: bash # shell is used for run steps to denote which shell to use to run the command